### ISSUE TITLE
Changelog Page Development Stage

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#356]
This issue tracks and monitors the progress of the development of the Changelog page. Attached to this is the list of all the tasks that need to be done.
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/docs/issues/524
- [ ] https://github.com/sourcegraph/docs/issues/525
- [ ] https://github.com/sourcegraph/docs/issues/526
- [ ] https://github.com/sourcegraph/docs/issues/527
- [ ] https://github.com/sourcegraph/docs/issues/528
- [ ] https://github.com/sourcegraph/docs/issues/529
- [ ] https://github.com/sourcegraph/docs/issues/530
- [ ] https://github.com/sourcegraph/docs/issues/531
- [ ] https://github.com/sourcegraph/docs/issues/532
- [ ] https://github.com/sourcegraph/docs/issues/533
- [ ] https://github.com/sourcegraph/docs/issues/534
- [ ] https://github.com/sourcegraph/docs/issues/535
```

**Comment by MaedahBatool** [comment]
@zahidalidev I have added all the tasks for you here. Let's track these now individually.

**Comment by zahidalidev** [comment]
Sure, thanks
