### ISSUE TITLE
Page for docs chatbot

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#441]
We need a page for our docs chatbot. Details in doc.
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/docs/issues/588
- [ ] https://github.com/sourcegraph/docs/issues/589
- [ ] https://github.com/sourcegraph/docs/issues/590
```
