### ISSUE TITLE
Changelog V2 changes

### ISSUE THREAD

**Issue by MaedahBatool** [sourcegraph/docs#622]
This issues tackles post-launch issues of the Changelog page.
```[tasklist]
### Tasks
- [ ] Add “Back to changelog” button similar to the blog
- [ ] Make the version a URL param like the topics
- [ ] For individual updates, can we have the styles match the blog (with bigger text, wider width, and clickable screenshots that expand to full view)
- [ ] Add multi-author/avatar support — Pending
- [ ] Fix issues with responsive
- [ ] OG image — Pending
```

**Comment by MaedahBatool** [comment]
@zahidalidev tracking all post launch issues here.
